### ISSUE TITLE
dokofile.yml

### ISSUE THREAD

**Issue by egoist** [egoist/doko#4]
A simpler format for docker-compose:

```yaml
# Add domain to /etc/hosts
myapp.test:
    port: 3000
    command: next
    # Enable some built-in services
    services:
        mysql:
            database: myapp
            password: xxx
            version: 8
        redis: true
```

Run `doko up` or `doko down` to start / stop the services

---

So yeah this will be a complete rewrite
